### ISSUE TITLE
will this be open-sourced ?

### ISSUE THREAD

**Issue by faradayin** [lu-wo/whisbert#1]
Just read the paper, very interesting! 
Can I see the code ?

**Comment by lu-wo** [comment]
Hi @faradayin ! Yes it will be open-sourced soon. I just wanna make sure the code is clean and well-documented. If you want I can give you access to the private version of the repo already :)

**Comment by ud0y** [comment]
When will it be open-sourced?

**Comment by lu-wo** [comment]
hi! sorry for the delay -- been working on other projects. I can put in on my list and push the code this weekend :)
